// Generated from src/data/resume-content.json by scripts/generate-resume-typst.cjs.
// Language: french
// PDF output: public/payton-pei-resume-fr.pdf
// Do not edit this file by hand.
#import "@preview/basic-resume:0.2.9": *

#let name = "Dong Payton Pei"
#let location = "Ottawa, ON"
#let email = "paytonpei01@gmail.com"
#let github = "github.com/mammut001"
#let linkedin = "www.linkedin.com/in/pd110"

#show: resume.with(
  author: name,
  location: location,
  email: email,
  github: github,
  linkedin: linkedin,
  accent-color: "#000000",
  font: "New Computer Modern",
  paper: "us-letter",
  author-position: left,
  personal-info-position: left,
)

== Résumé

Développeur logiciel et étudiant à la maîtrise à l'Université d'Ottawa. Ancien stagiaire chez Nokia et Ford, je crée des produits Web, de bureau, mobiles et d'IA avec TypeScript, React, Rust/Tauri, Swift et Kotlin.

== Formation

#edu(
  institution: "Université Carleton",
  location: "Ottawa, ON",
  dates: dates-helper(start-date: "2017", end-date: "2023"),
  degree: "Baccalauréat en informatique",
)

#edu(
  institution: "Université d'Ottawa",
  location: "Ottawa, ON",
  dates: "2024",
  degree: "Maîtrise en science et ingénierie des systèmes",
)

== Expérience

#work(
  title: "Stagiaire en développement logiciel",
  location: "Ottawa, ON",
  company: "Ford Motor Canada",
  dates: dates-helper(start-date: "Apr 2020", end-date: "Aug 2020"),
)
- Développement de scripts de tests unitaires en C++11 avec GoogleTest pour des composants logiciels automobiles.
- Intégration de l'exécution des tests dans Jenkins CI/CD au sein d'un processus Agile.

#work(
  title: "Stagiaire en test de logiciels",
  location: "Ottawa, ON",
  company: "Nokia Canada",
  dates: dates-helper(start-date: "Aug 2020", end-date: "Aug 2021"),
)
- Amélioration du code de test JavaScript/XML afin de renforcer la couverture, la maintenabilité et la fiabilité des régressions.
- Documentation de l'architecture système et des flux de données dans Confluence pour soutenir le développement interéquipes.

== Projets

#project(
  name: "Pipi Shrimp Agent",
  url: "github.com/mammut001/pipi-shrimp-agent",
)
- Création d'un agent IA de bureau local-first avec Rust, Tauri 2, React et TypeScript, prenant en charge le streaming multi-fournisseurs, les appels d'outils, l'orchestration de workflows et la mémoire par projet.

#project(
  name: "Resume Generator",
  url: "resume-tailor.paytonpei.top",
)
- Création et déploiement d'un éditeur de CV full-stack avec React, TypeScript, Vite et Node.

#project(
  name: "Focus Mint",
  url: "apps.apple.com/us/app/focus-mint-focus-timer-study/id6759029810",
)
- Mise en production d'une application de productivité SwiftUI pour iOS, watchOS et macOS, avec sessions Pomodoro, widgets, localisation multilingue, achats intégrés et synchronisation entre appareils.

#project(
  name: "Meet See U",
  url: "chatpart-website.vercel.app",
)
- Création d'un produit social d'IA full-stack avec Kotlin, Jetpack Compose, Next.

#project(
  name: "Conveyor",
  url: "github.com/mammut001/Conveyor",
)
- Création d'une plateforme d'automatisation Python pour Telegram et Feishu, capable d'acheminer les commandes vers des tâches de développement assistées par agent, des outils personnels et des opérations planifiées.

== Recherche

#extracurriculars(
  activity: "Amélioration d'images en faible luminosité avec DDBM",
  dates: dates-helper(start-date: "2024", end-date: "Présent"),
)
- Recherche sur l'amélioration d'images en faible luminosité avec DDBM, dans le prolongement des travaux Learning to See in the Dark.

== Compétences
- *Langages*: TypeScript, JavaScript, Python, Java, C++, Swift, Kotlin, Rust, HTML, CSS, Bash
- *Frameworks & données*: React, React Native, Next.js, SwiftUI, Jetpack Compose, Node.js, Tailwind CSS, Flask, Tauri 2, SQLite, MongoDB, Firebase, WebRTC, PyTorch, Typst, Mermaid
- *Tests & livraison*: GoogleTest, PyTest, SeleniumGrid, Jenkins, Docker

