// Generated from src/data/resume-content.json by scripts/generate-resume-typst.cjs.
// Language: english
// PDF output: public/payton-pei-resume.pdf
// Do not edit this file by hand.
#import "@preview/basic-resume:0.2.9": *

#let name = "Dong Payton Pei"
#let location = "Ottawa, ON"
#let email = "paytonpei01@gmail.com"
#let github = "github.com/mammut001"
#let linkedin = "www.linkedin.com/in/pd110"

#show: resume.with(
  author: name,
  location: location,
  email: email,
  github: github,
  linkedin: linkedin,
  accent-color: "#000000",
  font: "New Computer Modern",
  paper: "us-letter",
  author-position: left,
  personal-info-position: left,
)

== Summary

Software developer and Master of Engineering student in System Science and Engineering at the University of Ottawa. Former Nokia and Ford co-op developer/tester with experience building full-stack, desktop, mobile, and AI products using TypeScript, React, Rust/Tauri, Swift, Kotlin, and cloud APIs.

== Education

#edu(
  institution: "Carleton University",
  location: "Ottawa, ON",
  dates: dates-helper(start-date: "2017", end-date: "2023"),
  degree: "Bachelor of Computer Science",
)

#edu(
  institution: "University of Ottawa",
  location: "Ottawa, ON",
  dates: "2024",
  degree: "Master of Engineering in System Science and Engineering",
)

== Work Experience

#work(
  title: "Software Developer Co-op",
  location: "Ottawa, ON",
  company: "Ford Motor Canada",
  dates: dates-helper(start-date: "Apr 2020", end-date: "Aug 2020"),
)
#align(left)[
- Developed C++11 unit-test scripts with GoogleTest for automotive software components.
- Integrated test execution with Jenkins CI/CD in an Agile development workflow.
]

#work(
  title: "Software Tester Co-op",
  location: "Ottawa, ON",
  company: "Nokia Canada",
  dates: dates-helper(start-date: "Aug 2020", end-date: "Aug 2021"),
)
#align(left)[
- Improved JavaScript/XML test code to strengthen coverage, maintainability, and regression confidence.
- Documented system architecture and data flows in Confluence to support cross-team development.
]

== Projects

#project(
  name: "pipi-shrimp-agent",
  url: "github.com/mammut001/pipi-shrimp-agent",
)
#align(left)[
- Built a local-first AI desktop agent with Rust, Tauri 2, React, and TypeScript, supporting multi-provider streaming, tool calling, workflow orchestration, and project-scoped memory.
]

#project(
  name: "Resume Generator",
  url: "resume-tailor.paytonpei.top",
)
#align(left)[
- Built and deployed a full-stack resume editor with React, TypeScript, Vite, and Node.
]

#project(
  name: "Focus Mint",
  url: "apps.apple.com/us/app/focus-mint-focus-timer-study/id6759029810",
)
#align(left)[
- Shipped a SwiftUI productivity app for iOS, watchOS, and macOS with Pomodoro sessions, widgets, multilingual localization, in-app purchases, and cross-device synchronization.
]

#project(
  name: "Meet See U",
  url: "chatpart-website.vercel.app",
)
#align(left)[
- Built a native Android AI companion app with Kotlin and Jetpack Compose, featuring Firebase authentication, customizable character profiles, messaging, push-to-talk/VAD voice chat, semantic memory, and Stripe-paid character slots.
]

#project(
  name: "Conveyor",
  url: "github.com/mammut001/Conveyor",
)
#align(left)[
- Built a Python automation platform for Telegram and Feishu that routes commands to agent-assisted development tasks, personal tools, and scheduled operations.
]

== Research

#extracurriculars(
  activity: "Low-Light Image Enhancement with DDBM",
  dates: dates-helper(start-date: "2024", end-date: "Present"),
)
#align(left)[
- Conducting research on low-light image enhancement with DDBM, building on the Learning to See in the Dark research direction.
]

== Skills
- *Languages*: TypeScript, JavaScript, Python, Java, C++, Swift, Kotlin, Rust, HTML, CSS, Bash
- *Frameworks & Data*: React, React Native, Next.js, SwiftUI, Jetpack Compose, Node.js, Tailwind CSS, Flask, Tauri 2, SQLite, MongoDB, Firebase, WebRTC, PyTorch, Typst, Mermaid
- *Testing & Delivery*: GoogleTest, PyTest, SeleniumGrid, Jenkins, Docker

