// Generated from src/data/resume-content.json by scripts/generate-resume-typst.cjs.
// Language: chinese
// PDF output: public/payton-pei-resume-zh.pdf
// Do not edit this file by hand.
#import "@preview/basic-resume:0.2.9": *

#let name = "Dong Payton Pei"
#let location = "Ottawa, ON"
#let email = "paytonpei01@gmail.com"
#let github = "github.com/mammut001"
#let linkedin = "www.linkedin.com/in/pd110"

#show: resume.with(
  author: name,
  location: location,
  email: email,
  github: github,
  linkedin: linkedin,
  accent-color: "#000000",
  font: "New Computer Modern",
  paper: "us-letter",
  author-position: left,
  personal-info-position: left,
)

== 概述

软件工程师，专注于本地优先 AI 系统、开发者工具和生产级移动应用。曾在 Nokia 和 Ford 担任开发/测试实习生，目前就读于渥太华大学工程硕士，具备 Rust/Tauri、TypeScript/React、Python、SwiftUI、Kotlin/Jetpack Compose、LLM 工具调用和云端集成的实战经验。

== 教育经历

#edu(
  institution: "渥太华大学",
  location: "Ottawa, ON",
  dates: dates-helper(start-date: "2024", end-date: "至今"),
  degree: "系统工程硕士",
)

#edu(
  institution: "卡尔顿大学",
  location: "Ottawa, ON",
  dates: dates-helper(start-date: "2017", end-date: "2023"),
  degree: "计算机科学学士",
)

== 工作经历

#work(
  title: "软件测试实习生",
  location: "Ottawa, ON",
  company: "Nokia Canada",
  dates: dates-helper(start-date: "Aug 2020", end-date: "Aug 2021"),
)
#align(left)[
- 维护并扩展面向电信软件的 JavaScript/XML 自动化测试套件，提升回归覆盖率、代码鲁棒性和可维护性。
- 使用 Confluence 编写系统架构和数据流文档，支持开发、调试和跨团队知识传递。
]

#work(
  title: "软件开发实习生",
  location: "Ottawa, ON",
  company: "Ford Motor Canada",
  dates: dates-helper(start-date: "Apr 2020", end-date: "Aug 2020"),
)
#align(left)[
- 使用 C++11 和 GoogleTest 为汽车软件组件开发单元测试。
- 将自动化测试执行集成到敏捷开发流程中的 Jenkins CI 管道。
]

== 项目

#project(
  name: "皮皮虾助手",
  url: "github.com/mammut001/pipi-shrimp-agent",
)
#align(left)[
- 使用 Rust、Tauri 2、React、TypeScript 和 SQLite 构建本地优先的桌面 AI 智能体，支持多 Provider 流式输出、结构化工具调用、项目级记忆以及本地代码和文件执行。
- 实现可视化工作流编排、基于 CDP 的浏览器自动化、多智能体协作、上下文压缩，并通过 Rust 后端的 Tauri 命令层实现原生 Typst PDF/SVG 渲染。
]

#project(
  name: "Conveyor 自动化平台",
  url: "github.com/mammut001/Conveyor",
)
#align(left)[
- 构建自托管 Python 控制平面，在 VPS 上连接 Telegram、飞书与 Codex CLI，并在隔离的 Git worktree 中执行开发任务，支持 diff、应用、丢弃和取消控制。
- 设计持久化 SQLite 任务队列和安全层，包含操作员白名单、显式确认门禁、输出脱敏、审计日志、诊断、提醒和可选开发者工具集成。
]

#project(
  name: "Resume Generator 简历生成器",
  url: "resume-tailor.paytonpei.top",
)
#align(left)[
- 使用 React、TypeScript 和 Node.js 构建并部署全栈简历工作区，支持 PDF/文本导入、岗位描述定制、结构化编辑和基于 Typst 的 PDF/SVG 导出。
- 新增经 Zod 校验的后端路由、注重隐私的可观测性、Docker 部署，以及 Vitest 和 Playwright 自动化测试。
]

#project(
  name: "Focus Mint 专注计时器",
  url: "apps.apple.com/us/app/focus-mint-focus-timer-study/id6759029810",
)
#align(left)[
- 在 App Store 发布面向 iPhone、iPad 和 Apple Watch 的 SwiftUI 效率应用，支持专注会话、收益追踪、数据分析、自定义模式和多语言本地化。
- 实现 StoreKit 变现、WidgetKit 和 Live Activity 体验，以及通过 WatchConnectivity 实现 iPhone 与 Apple Watch 双向同步。
]

#pagebreak()

== 研究

#extracurriculars(
  activity: "基于 Bridge U-Net 与 DDBM 的极低照度 RAW 图像复原",
  dates: "2026",
)
#align(left)[
- 参与极低照度 RAW 图像复原研究，使用配对的 SID 和 ELD 图像，对比 Bridge U-Net、微调、少样本元学习以及受 DDBM 启发的特征空间方法。
- 研究并记录内存高效的 DDBM-Feature 变体，采用时间条件解码、对深层编码器特征的选择性桥接插值和三步确定性推理；在 598 张 SID Sony 测试图像上取得 26.12 dB PSNR 与 0.807 MS-SSIM。
]

== 技能
- *语言*: Python, TypeScript, JavaScript, Rust, Swift, Kotlin, C++, Java, Bash
- *框架*: React, Node.js, Tauri 2, SwiftUI, Jetpack Compose, Firebase, Tailwind CSS
- *AI 与系统*: LLM APIs, Tool Calling, Embeddings, SQLite, CDP Browser Automation, WatchConnectivity, StoreKit 2
- *测试与交付*: PyTest, Vitest, Playwright, GoogleTest, Jenkins, Docker

