// Generated from src/data/resume-content.json by scripts/generate-resume-typst.cjs.
// Language: english
// PDF output: public/payton-pei-resume.pdf
// Do not edit this file by hand.
#import "@preview/basic-resume:0.2.9": *

#let name = "Dong Payton Pei"
#let location = "Ottawa, ON"
#let email = "paytonpei01@gmail.com"
#let github = "github.com/mammut001"
#let linkedin = "www.linkedin.com/in/pd110"

#show: resume.with(
  author: name,
  location: location,
  email: email,
  github: github,
  linkedin: linkedin,
  accent-color: "#000000",
  font: "New Computer Modern",
  paper: "us-letter",
  author-position: left,
  personal-info-position: left,
)

== Summary

Software engineer building local-first AI systems, developer tools, and production mobile applications. Former Nokia and Ford co-op developer/tester and current Master of Engineering student at the University of Ottawa, with hands-on experience in Rust/Tauri, TypeScript/React, Python, SwiftUI, Kotlin/Jetpack Compose, LLM tool calling, and cloud integrations.

== Education

#edu(
  institution: "University of Ottawa",
  location: "Ottawa, ON",
  dates: dates-helper(start-date: "2024", end-date: "Present"),
  degree: "Master of Engineering in Systems Engineering",
)

#edu(
  institution: "Carleton University",
  location: "Ottawa, ON",
  dates: dates-helper(start-date: "2017", end-date: "2023"),
  degree: "Bachelor of Computer Science",
)

== Work Experience

#work(
  title: "Software Tester Co-op",
  location: "Ottawa, ON",
  company: "Nokia Canada",
  dates: dates-helper(start-date: "Aug 2020", end-date: "Aug 2021"),
)
#align(left)[
- Maintained and extended JavaScript/XML-based automated test suites for telecommunications software, improving regression coverage, code robustness, and maintainability.
- Authored system architecture and data-flow documentation in Confluence to support development, debugging, and cross-team knowledge transfer.
]

#work(
  title: "Software Developer Co-op",
  location: "Ottawa, ON",
  company: "Ford Motor Canada",
  dates: dates-helper(start-date: "Apr 2020", end-date: "Aug 2020"),
)
#align(left)[
- Developed C++11 unit tests with GoogleTest for automotive software components.
- Integrated automated test execution into Jenkins CI pipelines within an Agile development workflow.
]

== Projects

#project(
  name: "pipi-shrimp-agent",
  url: "github.com/mammut001/pipi-shrimp-agent",
)
#align(left)[
- Architected a local-first desktop AI agent using Rust, Tauri 2, React, TypeScript, and SQLite, with multi-provider streaming, structured tool calling, project-scoped memory, and local code and file execution.
- Implemented visual workflow orchestration, CDP browser automation, multi-agent collaboration, context compression, and native Typst PDF/SVG rendering through a Rust-backed Tauri command layer.
]

#project(
  name: "Conveyor",
  url: "github.com/mammut001/Conveyor",
)
#align(left)[
- Built a self-hosted Python control plane connecting Telegram and Feishu to Codex CLI on a VPS, executing development tasks inside isolated Git worktrees with diff, apply, discard, and cancellation controls.
- Designed a persistent SQLite job queue and safety layer with operator allowlists, explicit confirmation gates, output redaction, audit logging, diagnostics, reminders, and optional developer-tool integrations.
]

#pagebreak()

#project(
  name: "Resume Generator",
  url: "resume-tailor.paytonpei.top",
)
#align(left)[
- Built and deployed a full-stack React, TypeScript, and Node.js resume workspace supporting PDF/text import, job-description tailoring, structured editing, and Typst-backed PDF/SVG export.
- Added Zod-validated backend routes, privacy-conscious observability, Docker deployment, and automated testing with Vitest and Playwright.
]

#project(
  name: "Focus Mint",
  url: "apps.apple.com/us/app/focus-mint-focus-timer-study/id6759029810",
)
#align(left)[
- Shipped a SwiftUI productivity app on the App Store for iPhone, iPad, and Apple Watch, featuring focus sessions, earnings tracking, analytics, custom modes, and multilingual localization.
- Implemented StoreKit monetization, WidgetKit and Live Activity experiences, and bidirectional iPhone-Apple Watch synchronization using WatchConnectivity.
]

== Research

#extracurriculars(
  activity: "Low-Light RAW Image Restoration with Bridge U-Net and DDBM",
  dates: "2026",
)
#align(left)[
- Collaborated on an extreme low-light RAW image restoration study using paired SID and ELD images, comparing Bridge U-Net, fine-tuning, few-shot meta-learning, and a DDBM-inspired feature-space approach.
- Investigated and documented a memory-efficient DDBM-Feature variant using time-conditioned decoding, selective bridge interpolation over deep encoder features, and three-step deterministic inference; evaluated it at 26.12 dB PSNR and 0.807 MS-SSIM on 598 SID Sony test images.
]

== Skills
- *Languages*: Python, TypeScript, JavaScript, Rust, Swift, Kotlin, C++, Java, Bash
- *Frameworks*: React, Node.js, Tauri 2, SwiftUI, Jetpack Compose, Firebase, Tailwind CSS
- *AI & Systems*: LLM APIs, Tool Calling, Embeddings, SQLite, CDP Browser Automation, WatchConnectivity, StoreKit 2
- *Testing & Delivery*: PyTest, Vitest, Playwright, GoogleTest, Jenkins, Docker

