// Generated from src/data/resume-content.json by scripts/generate-resume-typst.cjs.
// Language: chinese
// PDF output: public/payton-pei-resume-zh.pdf
// Do not edit this file by hand.
#import "@preview/basic-resume:0.2.9": *

#let name = "Dong Payton Pei"
#let location = "Ottawa, ON"
#let email = "paytonpei01@gmail.com"
#let github = "github.com/mammut001"
#let linkedin = "www.linkedin.com/in/pd110"

#show: resume.with(
  author: name,
  location: location,
  email: email,
  github: github,
  linkedin: linkedin,
  accent-color: "#000000",
  font: "New Computer Modern",
  paper: "us-letter",
  author-position: left,
  personal-info-position: left,
)

== 概述

渥太华大学系统科学与工程硕士研究生，具备 Nokia 和 Ford 软件开发与测试实习经历。使用 TypeScript、React、Rust/Tauri、Swift、Kotlin 及云端 API 构建过全栈、桌面、移动端和 AI 产品。

== 教育经历

#edu(
  institution: "卡尔顿大学",
  location: "Ottawa, ON",
  dates: dates-helper(start-date: "2017", end-date: "2023"),
  degree: "计算机科学学士",
)

#edu(
  institution: "渥太华大学",
  location: "Ottawa, ON",
  dates: "2024",
  degree: "系统科学与工程硕士",
)

== 工作经历

#work(
  title: "软件开发实习生",
  location: "Ottawa, ON",
  company: "Ford Motor Canada",
  dates: dates-helper(start-date: "Apr 2020", end-date: "Aug 2020"),
)
#align(left)[
- 使用 C++11 和 GoogleTest 为汽车软件组件开发单元测试脚本。
- 将测试执行集成到 Jenkins CI/CD 流程中，参与敏捷开发。
]

#work(
  title: "软件测试实习生",
  location: "Ottawa, ON",
  company: "Nokia Canada",
  dates: dates-helper(start-date: "Aug 2020", end-date: "Aug 2021"),
)
#align(left)[
- 改进 JavaScript/XML 测试代码，提升代码覆盖率、可维护性和回归测试可靠性。
- 使用 Confluence 记录系统架构与数据流，支持跨团队协作开发。
]

== 项目

#project(
  name: "皮皮虾助手",
  url: "github.com/mammut001/pipi-shrimp-agent",
)
#align(left)[
- 使用 Rust、Tauri 2、React 和 TypeScript 构建本地优先的 AI 桌面助手，支持多 Provider 流式输出、工具调用、工作流编排和项目级记忆。
]

#project(
  name: "Resume Generator 简历生成器",
  url: "resume-tailor.paytonpei.top",
)
#align(left)[
- 使用 React、TypeScript、Vite 和 Node.
]

#project(
  name: "Focus Mint 专注计时器",
  url: "apps.apple.com/us/app/focus-mint-focus-timer-study/id6759029810",
)
#align(left)[
- 发布基于 SwiftUI 的 iOS、watchOS 和 macOS 效率应用，支持番茄钟会话、小组件、多语言本地化、应用内购买和跨设备同步。
]

#project(
  name: "Meet See U AI 社交应用",
  url: "chatpart-website.vercel.app",
)
#align(left)[
- 使用 Kotlin、Jetpack Compose、Next.
]

#project(
  name: "Conveyor 自动化平台",
  url: "github.com/mammut001/Conveyor",
)
#align(left)[
- 构建 Python 自动化平台，通过 Telegram 和飞书将指令路由到智能体辅助开发任务、个人工具和定时操作。
]

== 研究

#extracurriculars(
  activity: "基于 DDBM 的低光图像增强",
  dates: dates-helper(start-date: "2024", end-date: "至今"),
)
#align(left)[
- 围绕 DDBM 开展低光图像增强研究，延续 Learning to See in the Dark 方向的相关工作。
]

== 技能
- *语言*: TypeScript, JavaScript, Python, Java, C++, Swift, Kotlin, Rust, HTML, CSS, Bash
- *框架与数据*: React, React Native, Next.js, SwiftUI, Jetpack Compose, Node.js, Tailwind CSS, Flask, Tauri 2, SQLite, MongoDB, Firebase, WebRTC, PyTorch, Typst, Mermaid
- *测试与交付*: GoogleTest, PyTest, SeleniumGrid, Jenkins, Docker

