// Generated from src/data/resume-content.json by scripts/generate-resume-typst.cjs.
// Language: english
// PDF output: public/payton-pei-resume.pdf
// Do not edit this file by hand.
#import "@preview/basic-resume:0.2.9": *

#let name = "Payton Pei"
#let location = "Ottawa"
#let email = "paytonpei01@gmail.com"

#show: resume.with(
  author: name,
  location: location,
  email: email,
  phone: "+86 17640426168",
  accent-color: "#000000",
  font: ("Noto Sans", "Noto Sans CJK SC"),
  paper: "a4",
  lang: "en",
  font-size: 9.75pt,
  author-position: left,
  personal-info-position: left,
)

#set par(leading: 0.47em, spacing: 0.5em)
#link("https://github.com/mammut001")[GitHub: mammut001] | #link("https://www.linkedin.com/in/pd110/")[LinkedIn] | #link("https://cv.paytonpei.top")[cv.paytonpei.top]

== Summary

Systems Science and Engineering master's student at the University of Ottawa, graduating in December 2026 (expected). Software engineer building and fine-tuning AI systems with Python, PyTorch, Rust/Tauri and TypeScript/React; published LifeMint on the App Store. Former Nokia and Ford intern seeking new-grad AI application and developer-tools roles in Ottawa.

== Education

#edu(
  institution: "University of Ottawa",
  location: "",
  dates: dates-helper(start-date: "2024", end-date: "Dec 2026 (expected)"),
  degree: "Master of Systems Science and Engineering",
)

#edu(
  institution: "Carleton University",
  location: "",
  dates: dates-helper(start-date: "2017", end-date: "2023"),
  degree: "Bachelor of Computer Science",
)

== Projects

#project(
  name: "GaokaoTutor — LLM Fine-Tuning & Evaluation",
)
#align(left)[
- Fine-tuned Spark X2.5-4B with 4-bit QLoRA on an RTX 4090 using 161 tutoring traces; built reproducible data provenance, anti-contamination checks and a matched evaluation on a frozen 80-case unseen holdout.
- Reduced unsolicited solution dumping in hint/diagnosis cases from 100% to 13.5% and truncation from 57.5% to 0%; integrated the adapter into a Python tutor service and Expo prototype with deterministic math verification.
]

#project(
  name: "pipi-shrimp-agent",
  url: "github.com/mammut001/pipi-shrimp-agent",
)
#align(left)[
- Built a local-first desktop AI agent with Rust/Tauri, React/TypeScript and SQLite, integrating multiple LLM providers, structured tool calls and project memory.
- Implemented provider adapters, buffered SSE parsing and cancellation, plus CDP browser automation with failure recovery and context compression for long-running sessions.
]

#project(
  name: "LifeMint (formerly Focus Mint)",
  url: "apps.apple.com/us/app/lifemint/id6759029810",
)
#align(left)[
- Published a SwiftUI productivity app for iPhone, iPad and Apple Watch with focus sessions, earnings tracking and English, Chinese and French localization.
- Implemented StoreKit purchases, widgets, Live Activities and bidirectional iPhone–Apple Watch synchronization with WatchConnectivity.
]

== Work Experience

#work(
  title: "Teaching Assistant",
  location: "Ottawa, Canada",
  company: "Carleton University",
  dates: "2021",
)
#align(left)[
- Teaching assistant for Python 3 (Jan–Apr 2021) and JOUR 4401 (Sep–Dec 2021), covering relational databases, web crawling and data analysis.
]

#work(
  title: "Software Tester Intern",
  location: "Ottawa, Canada",
  company: "Nokia Canada",
  dates: dates-helper(start-date: "Sep 2020", end-date: "Aug 2021"),
)
#align(left)[
- Tested the legacy NFM-P client in the 7750 Service Router context using JavaScript, XML and the Mocha testing framework.
- Documented system architecture and data flows in Confluence.
]

#work(
  title: "Software Engineer Intern",
  location: "Ottawa, Canada",
  company: "Ford Motor Canada",
  dates: dates-helper(start-date: "May 2020", end-date: "Aug 2020"),
)
#align(left)[
- Contributed to in-vehicle and cloud connectivity software in C++11 on QNX/Linux.
- Wrote GoogleTest unit tests, fixed bugs and maintained technical documentation; used Jenkins in the CI/CD workflow.
]

== Research

#extracurriculars(
  activity: "Low-Light RAW Image Restoration with Bridge U-Net and DDBM",
  dates: "2026",
)
#align(left)[
- Responsible for the initial DDBM implementation in a collaborative low-light RAW image restoration study using SID and ELD data.
- The project evaluated a DDBM-Feature variant at 26.12 dB PSNR and 0.807 MS-SSIM on 598 SID Sony test images.
]

== Skills
- *Languages*: Python, TypeScript, JavaScript, Rust, Swift, C++
- *Frameworks*: React, Node.js, Tauri 2, SwiftUI
- *AI & Systems*: PyTorch, Transformers, PEFT/TRL, QLoRA, MLX, LLM APIs, Tool Calling, MCP, SQLite
- *Testing & Delivery*: PyTest, Vitest, Playwright, GoogleTest, Jenkins, Docker
- *Additional*: CDP Browser Automation, WatchConnectivity, StoreKit 2

