// Generated from src/data/resume-content.json by scripts/generate-resume-typst.cjs.
// Language: french
// PDF output: public/payton-pei-resume-fr.pdf
// Do not edit this file by hand.
#import "@preview/basic-resume:0.2.9": *

#let name = "Dong Payton Pei"
#let location = "Ottawa, ON"
#let email = "paytonpei01@gmail.com"
#let github = "github.com/mammut001"
#let linkedin = "www.linkedin.com/in/pd110"

#show: resume.with(
  author: name,
  location: location,
  email: email,
  github: github,
  linkedin: linkedin,
  accent-color: "#000000",
  font: "New Computer Modern",
  paper: "us-letter",
  author-position: left,
  personal-info-position: left,
)

== Résumé

Ingénieur logiciel spécialisé dans les systèmes d'IA local-first, les outils de développement et les applications mobiles de production. Ancien stagiaire développeur/testeur chez Nokia et Ford et étudiant actuel à la maîtrise en ingénierie à l'Université d'Ottawa, avec une expérience pratique de Rust/Tauri, TypeScript/React, Python, SwiftUI, Kotlin/Jetpack Compose, des appels d'outils LLM et des intégrations cloud.

== Formation

#edu(
  institution: "Université d'Ottawa",
  location: "Ottawa, ON",
  dates: dates-helper(start-date: "2024", end-date: "Présent"),
  degree: "Maîtrise en ingénierie des systèmes",
)

#edu(
  institution: "Université Carleton",
  location: "Ottawa, ON",
  dates: dates-helper(start-date: "2017", end-date: "2023"),
  degree: "Baccalauréat en informatique",
)

== Expérience

#work(
  title: "Stagiaire en test de logiciels",
  location: "Ottawa, ON",
  company: "Nokia Canada",
  dates: dates-helper(start-date: "Aug 2020", end-date: "Aug 2021"),
)
#align(left)[
- Maintenance et extension de suites de tests automatisés JavaScript/XML pour des logiciels de télécommunications, améliorant la couverture de régression, la robustesse et la maintenabilité.
- Rédaction de documentation sur l'architecture système et les flux de données dans Confluence pour soutenir le développement, le débogage et le transfert de connaissances interéquipes.
]

#work(
  title: "Stagiaire en développement logiciel",
  location: "Ottawa, ON",
  company: "Ford Motor Canada",
  dates: dates-helper(start-date: "Apr 2020", end-date: "Aug 2020"),
)
#align(left)[
- Développement de tests unitaires C++11 avec GoogleTest pour des composants logiciels automobiles.
- Intégration de l'exécution automatisée des tests dans des pipelines Jenkins CI au sein d'un processus Agile.
]

== Projets

#project(
  name: "Pipi Shrimp Agent",
  url: "github.com/mammut001/pipi-shrimp-agent",
)
#align(left)[
- Architecture d'un agent IA de bureau local-first avec Rust, Tauri 2, React, TypeScript et SQLite, avec streaming multi-fournisseurs, appels d'outils structurés, mémoire par projet et exécution locale de code et de fichiers.
- Mise en œuvre d'une orchestration visuelle de workflows, de l'automatisation de navigateur par CDP, de la collaboration multi-agents, de la compression de contexte et du rendu natif Typst PDF/SVG via une couche de commandes Tauri en Rust.
]

#project(
  name: "Conveyor",
  url: "github.com/mammut001/Conveyor",
)
#align(left)[
- Création d'un plan de contrôle Python auto-hébergé reliant Telegram et Feishu à Codex CLI sur un VPS, exécutant des tâches de développement dans des worktrees Git isolés avec contrôles de diff, application, abandon et annulation.
- Conception d'une file de tâches SQLite persistante et d'une couche de sécurité avec listes d'opérateurs autorisés, confirmations explicites, masquage de sorties, journalisation d'audit, diagnostics, rappels et intégrations optionnelles d'outils de développement.
]

#pagebreak()

#project(
  name: "Resume Generator",
  url: "resume-tailor.paytonpei.top",
)
#align(left)[
- Création et déploiement d'un espace de travail de CV full-stack avec React, TypeScript et Node.js, prenant en charge l'importation PDF/texte, l'adaptation aux offres d'emploi, l'édition structurée et l'export PDF/SVG avec Typst.
- Ajout de routes backend validées par Zod, d'une observabilité respectueuse de la confidentialité, d'un déploiement Docker et de tests automatisés avec Vitest et Playwright.
]

#project(
  name: "Focus Mint",
  url: "apps.apple.com/us/app/focus-mint-focus-timer-study/id6759029810",
)
#align(left)[
- Publication sur l'App Store d'une application de productivité SwiftUI pour iPhone, iPad et Apple Watch, avec sessions de concentration, suivi des gains, analytique, modes personnalisés et localisation multilingue.
- Mise en œuvre de la monétisation StoreKit, d'expériences WidgetKit et Live Activity, ainsi que d'une synchronisation bidirectionnelle iPhone-Apple Watch avec WatchConnectivity.
]

== Compétences
- *Langages*: Python, TypeScript, JavaScript, Rust, Swift, Kotlin, C++, Java, Bash
- *Frameworks*: React, Node.js, Tauri 2, SwiftUI, Jetpack Compose, Firebase, Tailwind CSS
- *IA & systèmes*: LLM APIs, Tool Calling, Embeddings, SQLite, CDP Browser Automation, WatchConnectivity, StoreKit 2
- *Tests & livraison*: PyTest, Vitest, Playwright, GoogleTest, Jenkins, Docker

