// Generated from src/data/resume-content.json by scripts/generate-resume-typst.cjs.
// Language: french
// PDF output: public/payton-pei-resume-fr.pdf
// Do not edit this file by hand.
#import "@preview/basic-resume:0.2.9": *

#let name = "Dong Payton Pei"
#let location = "Ottawa, ON"
#let email = "paytonpei01@gmail.com"
#let github = "github.com/mammut001"
#let linkedin = "www.linkedin.com/in/pd110"

#show: resume.with(
  author: name,
  location: location,
  email: email,
  github: github,
  linkedin: linkedin,
  accent-color: "#000000",
  font: "New Computer Modern",
  paper: "us-letter",
  author-position: left,
  personal-info-position: left,
)

== Résumé

Bachelier en informatique de l'Université Carleton avec une vaste expérience de stage coopératif en test et développement de logiciels. Compétent en TypeScript, JavaScript, Python et diverses autres technologies. Cherche un poste d'ingénieur logiciel pour tirer parti de mes compétences en conception, développement et test de solutions logicielles.

== Formation

#edu(
  institution: "Université d'Ottawa",
  location: "Ottawa, ON",
  dates: "Présent",
  degree: "Génie des systèmes et de l'ingénierie",
)

#edu(
  institution: "L'Université Carleton",
  location: "Ottawa, ON",
  dates: dates-helper(start-date: "2017", end-date: "2023"),
  degree: "Baccalauréat en informatique",
)

== Expérience

#work(
  title: "Stagiaire en développement logiciel",
  location: "Ottawa, ON",
  company: "Ford Motor Canada",
  dates: dates-helper(start-date: "Apr 2020", end-date: "Aug 2020"),
)
- Participation au développement Agile, développement de scripts de test unitaire utilisant le framework Google Test de C++11, et utilisation de Jenkins pour le CI/CD.

#work(
  title: "Stagiaire en test de logiciels",
  location: "Ottawa, ON",
  company: "Nokia Canada",
  dates: dates-helper(start-date: "Aug 2020", end-date: "Aug 2021"),
)
- Amélioration du code JavaScript/XML pour une meilleure couverture de code et robustesse.
- Production de documents de conception utilisant Confluence Pages pour l'architecture système et les flux de données.

== Projets

#project(
  name: "Pipi Shrimp Agent",
  url: "github.com/mammut001/pipi-shrimp-agent",
)
- Un agent IA de bureau haute performance construit avec Tauri v2.

#project(
  name: "Meet See U",
  url: "chatpart-website.vercel.app",
)
- Une application sociale IA complète avec des compagnons virtuels dotés d'une mémoire vectorielle persistante et d'un clonage de voix personnalisé.

#project(
  name: "Focus Mint",
  url: "apps.apple.com/us/app/focus-mint-focus-timer-study/id6759029810",
)
- Une application utilitaire premium pour iOS, watchOS et macOS conçue pour améliorer la productivité via des minuteurs de style Pomodoro et le suivi de sessions.

#project(
  name: "Optimisation des Systèmes - Smart Path",
  url: "system-optimizaion.vercel.app",
)
- Une plateforme sophistiquée de visualisation d'algorithmes prenant en charge la théorie des graphes (Dijkstra, A\*, BFS/DFS), l'optimisation (Simplex, Branch & Bound) et l'apprentissage automatique (Perceptrons).

#project(
  name: "RentWise",
  url: "github.com/random-char1198/Coin-Web-Crawler",
)
- Mise en œuvre de l'inscription et de la connexion Google pour l'authentification des utilisateurs, stockant de manière sécurisée les informations des utilisateurs dans Firebase.

== Recherche

#extracurriculars(
  activity: "Learning to See in the Dark 2018 Enhancement with DDBM",
  dates: dates-helper(start-date: "2024", end-date: "Présent"),
)
- Recherche sur l'amélioration du traitement d'images en faible luminosité utilisant DDBM basé sur l'article fondateur 'Learning to See in the Dark'.

== Compétences
- *Langages*: TypeScript, JavaScript, Python, Java, C++, Swift, Rust, HTML, CSS, Bash
- *Frameworks & données*: NextJS, TailwindCSS, Flask, Tauri v2, SQLite, MongoDB, JQuery
- *Tests & livraison*: PyTest, GTest, SeleniumGrid, Jenkins, Docker, Vagrant
- *Outils & plateformes*: GitHub, Jira, Confluence, Linux, AWS, OpenStack, IntelliJ, PostMan, Windows10, Visual Studio, Typst, Mermaid, Object-Oriented Programming

