// Generated from src/data/resume-content.json by scripts/generate-resume-typst.cjs.
// Language: chinese
// PDF output: public/payton-pei-resume-zh.pdf
// Do not edit this file by hand.
#import "@preview/basic-resume:0.2.9": *

#let name = "裴栋 | Payton Pei"
#let location = "杭州 / 上海"
#let email = "paytonpei01@gmail.com"

#show: resume.with(
  author: name,
  location: location,
  email: email,
  phone: "+86 17640426168",
  accent-color: "#000000",
  font: ("Noto Sans", "Noto Sans CJK SC"),
  paper: "a4",
  lang: "zh",
  font-size: 9.75pt,
  author-position: left,
  personal-info-position: left,
)

#set par(leading: 0.47em, spacing: 0.5em)
#link("https://github.com/mammut001")[GitHub: mammut001] | #link("https://www.linkedin.com/in/pd110/")[LinkedIn] | #link("https://cv.paytonpei.top")[cv.paytonpei.top]

== 概述

渥太华大学系统科学与工程硕士在读，预计 2026 年 12 月毕业，求职杭州 / 上海 AI 应用与开发者工具方向的应届软件工程岗位。使用 Python/PyTorch、Rust/Tauri 与 TypeScript/React 开发并微调 AI 系统；LifeMint 已在 App Store 发布。曾在 Nokia、Ford 实习。

== 教育经历

#edu(
  institution: "渥太华大学",
  location: "",
  dates: dates-helper(start-date: "2024", end-date: "2026 年 12 月（预计）"),
  degree: "系统科学与工程硕士",
)

#edu(
  institution: "卡尔顿大学",
  location: "",
  dates: dates-helper(start-date: "2017", end-date: "2023"),
  degree: "计算机科学学士",
)

== 项目

#project(
  name: "GaokaoTutor — 大模型微调与评测",
)
#align(left)[
- 在 RTX 4090 上使用 4-bit QLoRA 微调 Spark X2.5-4B，构建 161 条教学轨迹，并实现数据溯源、污染检测及 80 题冻结未见集对照评测。
- 将提示/诊断场景中未经请求的完整解答率从 100% 降至 13.5%、输出截断率从 57.5% 降至 0%；将适配器接入 Python 教学服务与 Expo 原型，并加入确定性数学校验。
]

#project(
  name: "桌面 AI Agent（pipi-shrimp-agent）",
  url: "github.com/mammut001/pipi-shrimp-agent",
)
#align(left)[
- 使用 Rust/Tauri、React/TypeScript 与 SQLite 构建本地优先桌面 AI Agent，集成多模型接入、结构化工具调用与项目记忆。
- 实现供应商适配、SSE 缓冲解析与取消机制，并支持 CDP 浏览器自动化、失败恢复和长会话上下文压缩。
]

#project(
  name: "LifeMint（原 Focus Mint）",
  url: "apps.apple.com/us/app/lifemint/id6759029810",
)
#align(left)[
- 在 App Store 发布面向 iPhone、iPad 和 Apple Watch 的 SwiftUI 应用，提供专注会话、收益追踪及中英法三语支持。
- 实现 StoreKit 内购、桌面组件、实时活动，以及基于 WatchConnectivity 的手机与手表双向同步。
]

== 工作经历

#work(
  title: "助教（兼职）",
  location: "加拿大渥太华",
  company: "Carleton University",
  dates: "2021",
)
#align(left)[
- 2021 年 1–4 月担任 Python 3 助教；9–12 月担任 JOUR 4401 助教，课程涉及关系型数据库、网络爬虫与数据分析。
]

#work(
  title: "软件测试实习生",
  location: "加拿大渥太华",
  company: "Nokia Canada",
  dates: dates-helper(start-date: "Sep 2020", end-date: "Aug 2021"),
)
#align(left)[
- 围绕 7750 Service Router，使用 JavaScript、XML 与 Mocha 测试框架测试旧版 NFM-P 客户端。
- 编写 Confluence 设计文档，记录系统架构与数据流。
]

#work(
  title: "软件工程实习生",
  location: "加拿大渥太华",
  company: "Ford Motor Canada",
  dates: dates-helper(start-date: "May 2020", end-date: "Aug 2020"),
)
#align(left)[
- 参与车载与云连接软件子系统开发，在 QNX/Linux 环境下使用 C++11 编写 GoogleTest 单元测试、修复缺陷并维护技术文档；在 CI/CD 工作流中使用 Jenkins。
]

== 研究

#extracurriculars(
  activity: "基于 Bridge U-Net 与 DDBM 的极低照度 RAW 图像复原",
  dates: "2026",
)
#align(left)[
- 参与基于 SID、ELD 数据的极低照度 RAW 图像复原研究，负责 DDBM 初版实现。
- 项目中的 DDBM-Feature 变体在 598 张 SID Sony 测试图像上取得 26.12 dB PSNR 与 0.807 MS-SSIM。
]

== 技能
- *语言*: Python, TypeScript, JavaScript, Rust, Swift, C++
- *框架*: React, Node.js, Tauri 2, SwiftUI
- *AI 与系统*: PyTorch, Transformers, PEFT/TRL, QLoRA, MLX, LLM APIs, Tool Calling, MCP, SQLite
- *测试与交付*: PyTest, Vitest, Playwright, GoogleTest, Jenkins, Docker
- *补充*: CDP Browser Automation, WatchConnectivity, StoreKit 2

